spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8085